### ISSUE TITLE
mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')

### ISSUE THREAD

**Issue by PabloArrow** [biobakery/phylophlan#101]
everytime I call the phylophlan command (even phylophlan --v) I get this error.

Traceback (most recent call last):
  File "/Users/<myuser>/miniconda3/bin/phylophlan", line 5, in <module>
    from phylophlan.phylophlan import phylophlan_main
  File "/Users/<myuser>/miniconda3/lib/python3.9/site-packages/phylophlan/phylophlan.py", line 21, in <module>
    from Bio import SeqIO
  File "/Users/<myuser>/miniconda3/lib/python3.9/site-packages/Bio/SeqIO/__init__.py", line 374, in <module>
    from Bio.Align import MultipleSeqAlignment
  File "/Users/<myuser>/miniconda3/lib/python3.9/site-packages/Bio/Align/__init__.py", line 18, in <module>
    from Bio.Align import _aligners
ImportError: dlopen(/Users/<myuser>/miniconda3/lib/python3.9/site-packages/Bio/Align/_aligners.cpython-39-darwin.so, 0x0002): tried: '/Users/<myuser>/miniconda3/lib/python3.9/site-packages/Bio/Align/_aligners.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Users/<myuser>/miniconda3/lib/python3.9/site-packages/Bio/Align/_aligners.cpython-39-darwin.so' (no such file), '/Users/<myuser>/miniconda3/lib/python3.9/site-packages/Bio/Align/_aligners.cpython-39-darwin.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))

I have a M1 macbook pro.
Metaphlan works ok

**Comment by fasnicar** [comment]
Hi, reading through the error you reported it feels to me that there is a problem with the Biopython library. Please, check if there exists a Biopython version compatible with your architecture, otherwise, you should consider using a different machine with a compatible architecture.

Many thanks,
Francesco
