### ISSUE TITLE
AttributeError: module 'collections' has no attribute 'MutableMapping'

### ISSUE THREAD

**Issue by Guan06** [biobakery/phylophlan#96]
Hi,

I installed phylophlan 3.0 from bioconda, and tried to download the databases via:

_phylophlan -d phylophlan --databases_folder ./_

But got error message as below:
Traceback (most recent call last):
  File "/home/.conda/envs/phylophlan/bin/phylophlan", line 7, in <module>
    from phylophlan.phylophlan import phylophlan_main
  File "/home/.conda/envs/phylophlan/lib/python3.10/site-packages/phylophlan/phylophlan.py", line 34, in <module>
    import dendropy
  File "/home/.conda/envs/phylophlan/lib/python3.10/site-packages/dendropy/__init__.py", line 25, in <module>
    from dendropy.dataio.nexusprocessing import get_rooting_argument
  File "/home/.conda/envs/phylophlan/lib/python3.10/site-packages/dendropy/dataio/__init__.py", line 21, in <module>
    from dendropy.dataio import newickreader
  File "/home/.conda/envs/phylophlan/lib/python3.10/site-packages/dendropy/dataio/newickreader.py", line 30, in <module>
    from dendropy.dataio import nexusprocessing
  File "/home/.conda/envs/phylophlan/lib/python3.10/site-packages/dendropy/dataio/nexusprocessing.py", line 31, in <module>
    from dendropy.utility import container
  File "/home/.conda/envs/phylophlan/lib/python3.10/site-packages/dendropy/utility/container.py", line 357, in <module>
    class CaseInsensitiveDict(collections.MutableMapping):
AttributeError: module 'collections' has no attribute 'MutableMapping'

I think it is due to the python version, that  in python 3.10, the attribute MutableMapping from the module collections have been removed, but don't know how to fix this problem though..

Many thanks and best,
Rui

**Comment by fasnicar** [comment]
Dear Rui, many thanks for reporting this. You can downgrade your python in the `phylophlan` conda env to a version <3.10.
For instance,
```conda install python=3.8```

Many thanks,
Francesco

**Comment by Guan06** [comment]
Thanks very much, this fixed the problem!
Sorry.. forget to close the issue earlier..

Best,
Rui
