### ISSUE TITLE
UnboundLocalError: local variable 'uniprotkb2uniref90' referenced before assignment

### ISSUE THREAD

**Issue by llk578496** [biobakery/phylophlan#98]
Hello @fasnicar 

We just tried to set up the database for _Burkholderia pseudomallei_, but we got the following error messages.

**Error message:**
`[e] unable convert UniProtKB ID to UniRef90 ID
Traceback (most recent call last):
  File "/home/gilmansiu3/miniconda3/envs/phylophlan/bin/phylophlan_setup_database", line 10, in <module>
    sys.exit(phylophlan_setup_database())
  File "/home/gilmansiu3/miniconda3/envs/phylophlan/lib/python3.7/site-packages/phylophlan/phylophlan_setup_database.py", line 407, in phylophlan_setup_database
    get_core_proteins(taxa2core_file_latest, args.get_core_proteins, args.output, args.output_extension, verbose=args.verbose)
  File "/home/gilmansiu3/miniconda3/envs/phylophlan/lib/python3.7/site-packages/phylophlan/phylophlan_setup_database.py", line 333, in get_core_proteins
    for uniref90_id in (x[1].split('_')[-1] for x in uniprotkb2uniref90[1:]):
UnboundLocalError: local variable 'uniprotkb2uniref90' referenced before assignment`

**Command line:**
`phylophlan_setup_database -g s__Burkholderia_pseudomallei -o ${AWD}/01_ref/01.2_phylophlan_db/01.2.1_Burkholderia_pseudomallei/s__Burkholderia_pseudomallei --verbose 2>&1 | tee ${AWD}/01_ref/01.2_phylophlan_db/01.2.1_Burkholderia_pseudomallei/logs/phylophlan_setup_database.log`

**Log:**
[phylophlan_setup_database.log](https://github.com/biobakery/phylophlan/files/9388274/phylophlan_setup_database.log)

We really look forward to your reply!
Thank you very much!

Eddie

**Comment by maxibor** [comment]
I'm unfortunately getting the same error message :(
Also side note, since the species _Lactobacillus plantarum_ has been renamed in _Lactiplantibacillus plantarum_ I unfortunately have to used an outdated species name with Phylophlan.

```bash
$ phylophlan --version
PhyloPhlAn version 3.0.67 (24 August 2022)
$ phylophlan_setup_database \
-g s__Lactobacillus_plantarum \
-o uniref_90/lactiplantibacillus_plantarum \
--verbose 2>&1 | tee logs/phylophlan_setup_database.log
```
[phylophlan_setup_database.log](https://github.com/biobakery/phylophlan/files/9438437/phylophlan_setup_database.log)

**Comment by fasnicar** [comment]
Thank you both for reporting this issue.
From a quick look it seems that this is due to old IDs in the PhyloPhlAn coreness files that are not resolved by UniProt into newer UniRef90 IDs.
I have to say that this to be fixed might take a bit as updating all UniRef IDs is done externally from PhyloPhlAn and will require re-annotating all genomes that were used in building bioBakery 3.
I'll let you know here as soon as there are updates on this.

Many thanks,
Francesco

**Comment by llk578496** [comment]
Thank you so much! We really look forward to it!

**Comment by fasnicar** [comment]
Hi all, with commit c64a75fc3841507ce4a6264616f81140bce01009 this issue should be fixed. Can I ask you to pull the latest version from the repository and test it?

I'll then make a new release in conda bringing this fix.

Many thanks,
Francesco

**Comment by llk578496** [comment]
Thank you for the fix!

We tried to create a new environment named as `phylophlan-dev` with `python=3.10.6` with the below command. 
`mamba create -n phylophlan-dev python=3.10.6`

Then, we cloned the phylophlan repository and finished the setup with the following commands.
```
git clone https://github.com/biobakery/phylophlan
cd phylophlan
python setup.py install
```

Everything seems to be fine. However, when we tried to test the `phylophlan_setup_database`, we got the following errors:
```
(phylophlan-dev) gilmansiu3@gilmansiu3-Z490-AORUS-ULTRA:/mnt/data/Species-specific/PPS/ONT/Analysis$ phylophlan_setup_database -g s__Burkholderia_pseudomallei -o ${AWD}/01_ref/01.2_phylophlan_db/01.2.1_Burkholderia_pseudomallei/s__Burkholderia_pseudomallei --verbose 2>&1 | tee ${AWD}/01_ref/01.2_phylophlan_db/01.2.1_Burkholderia_pseudomallei/logs/phylophlan_setup_database.log
Traceback (most recent call last):
  File "/home/gilmansiu3/miniconda3/envs/phylophlan-dev/bin/phylophlan_setup_database", line 33, in <module>
    sys.exit(load_entry_point('PhyloPhlAn==3.0.3', 'console_scripts', 'phylophlan_setup_database')())
  File "/home/gilmansiu3/miniconda3/envs/phylophlan-dev/bin/phylophlan_setup_database", line 25, in importlib_load_entry_point
    return next(matches).load()
  File "/home/gilmansiu3/miniconda3/envs/phylophlan-dev/lib/python3.10/importlib/metadata/__init__.py", line 171, in load
    module = import_module(match.group('module'))
  File "/home/gilmansiu3/miniconda3/envs/phylophlan-dev/lib/python3.10/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1006, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 688, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 883, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "/home/gilmansiu3/miniconda3/envs/phylophlan-dev/lib/python3.10/site-packages/PhyloPhlAn-3.0.3-py3.10.egg/phylophlan/phylophlan_setup_database.py", line 30, in <module>
    import requests
ModuleNotFoundError: No module named 'requests'
```

May I know is it the right way to pull the repository and test the `phylophlan_setup_database`?

Thank you very much!

Best regards,
Eddie

**Comment by fasnicar** [comment]
Ah right! Sorry, I forgot to mention that the new APIs from UniProt need the `requests` package to be installed. You can add it to your `phylophlan-dev` by running:

```
(phylophlan-dev) $ conda install -c conda-forge requests
```

**Comment by llk578496** [comment]
The `phylophlan_setup_database` looks fine now!
[phylophlan_setup_database.log](https://github.com/biobakery/phylophlan/files/9555832/phylophlan_setup_database.log)

**Comment by fasnicar** [comment]
Thank you for testing it out, I'm closing this then!
